import type { Metadata } from "next";
import Header from "@/components/global/Header";
import{ Abel } from 'next/font/google'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const agel = Abel({
  subsets: ['latin'],
  weight: '400'
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${agel.className} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
